### ISSUE TITLE
Azure Gov Cloud Support

### ISSUE THREAD

**Issue by erburk** [F5Networks/f5-telemetry-streaming#112]
### Is your feature request related to a problem? Please describe.
Azure Sentinel customers need to be able to deliver to instances running in Azure Gov Cloud (Azure.US).  Today the in product REST connector only delivers to Azure.com.

### Describe the solution you'd like
Enable configurability for which Azure Sentinel cloud endpoint is to be used for delivery of F5 data.  Could be configuration file entry or UI.

**Comment by dstokesf5** [comment]
@erburk Thank you for your feedback. Have you tried using the region property to select an Azure Gov region? https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#region-property

**Comment by dstokesf5** [comment]
This issue is being closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
