### ISSUE TITLE
Azure Sentinel Streaming - Table Name error

### ISSUE THREAD

**Issue by erburk** [F5Networks/f5-telemetry-streaming#131]
### Environment
* Telemetry Streaming Version: f5-telemetry-1.19.0-3.noarch 
* BIG-IP Version: 14.1.2

### Summary
F5 BIG-IP logs are being ingested into F5Telemetry_event_CL but all queries, workbooks and connectors expect the logs to be ingested into F5Telemetry_LTM_CL, F5Telemetry_ASM_CL

### Steps To Reproduce
https://devcentral.f5.com/s/articles/Integrating-the-F5-BIGIP-with-Azure-Sentinel

2. Observe the following error response:
Wrong table name

### Expected Behavior
Logs should be ingested into:
F5Telemetry_LTM_CL
F5Telemetry_ASM_CL

### Actual Behavior
Logs are being ingested into F5Telemetry_event_CL
![image](https://user-images.githubusercontent.com/5330902/118085513-d005cb00-b3c2-11eb-89e5-c34964d4499e.png)

**Comment by aleixsb** [comment]
### Environment
* Telemetry Streaming Version: f5-telemetry-1.19.0-3.noarch 
* BIG-IP Version: 14.1.2


### Summary
F5 BIG-IP logs are being ingested into F5Telemetry_event_CL but all queries, workbooks and connectors expect the logs to be ingested into F5Telemetry_LTM_CL, F5Telemetry_ASM_CL


### Steps To Reproduce
https://devcentral.f5.com/s/articles/Integrating-the-F5-BIGIP-with-Azure-Sentinel

2. Observe the following error response:
Wrong table name

### Expected Behavior
Logs should be ingested into:
F5Telemetry_LTM_CL
F5Telemetry_ASM_CL

### Actual Behavior
Logs are being ingested into F5Telemetry_event_CL
![image](https://user-images.githubusercontent.com/5330902/118085513-d005cb00-b3c2-11eb-89e5-c34964d4499e.png)

**Comment by dstokesf5** [comment]
I have updated the issue description using the information from the comment that appears to be using the bug template. I have also added the labels that are usually added by a template. Please be sure to use a template in the future when filing an issue so that our tooling and notifications work properly.

**Comment by michaelebbels** [comment]
I can confirm I'm having the same issue with LTM logging.

Environment

    Telemetry Streaming Version: f5-telemetry-1.19.0-3.noarch
    BIG-IP Version: 	15.1.2.1

Summary

F5 BIG-IP logs are being ingested into F5Telemetry_event_CL but all queries, workbooks and connectors expect the logs to be ingested into F5Telemetry_LTM_CL
Steps To Reproduce

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html#requestlog

    Observe the following error response:
    Wrong table name

Expected Behavior

Logs should be ingested into:
F5Telemetry_LTM_CL

Actual Behavior
F5Telemetry_events_CL

**Comment by aleixsb** [comment]
hey @michaelebbels can you share the error on request logging profile?

**Comment by dstokesf5** [comment]
@aleixsb are you able to share your request logging profile? I may be able to spot an issue with it. It sounds like @michaelebbels may have had the `request-log-template` property configured in a way that resulted in Telemetry Streaming failing to recognize it as an LTM event.

**Comment by aleixsb** [comment]
Hi Daniel,

Thanks! finally I managed to fix the issue, there was an error with the
template which I guess was causing the problem.

Best regards,
-----
Aleix Sala Bach
