### ISSUE TITLE
Need telemetry logging of metrics and logs to Oracle Cloud Logging for F5 deployments in Oracle Cloud

### ISSUE THREAD

**Issue by cnad001** [F5Networks/f5-telemetry-streaming#150]
### Is your feature request related to a problem? Please describe.
For F5 deployments in Oracle Cloud, Need Metric logging and syslog logging to Oracle Cloud logging similar to AWS, Azure

Similar to

Azure:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#microsoft-azure-log-analytics
ex.
https://github.com/F5Networks/f5-azure-arm-templates-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L251

AWS:
https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#aws-cloudwatch
ex.
https://github.com/F5Networks/f5-aws-cloudformation-v2/blob/main/examples/autoscale/bigip-configurations/runtime-init-conf-payg.yaml#L217

### Describe the solution you'd like
Native telemetry streaming of logs and metrics using the F5 telemetry module to Oracle Cloud Logging

### Describe alternatives you've considered
Use the remote logging or use Kafka streaming. Both have a lot of additional overhead and maintenance

**Comment by dstokesf5** [comment]
Thank you for resubmitting this issue.

**Comment by cnad001** [comment]
Thank you for releasing the telemetry logging feature to stream logs to Google StackDriver for Google Cloud Provider 
It would be really great if we can have native telemetry logging support for Oracle Cloud as we are actively using F5s in Oracle Cloud and it is extremely tedious otherwise to get logs from F5s in Oracle Cloud logging

**Comment by dstokesf5** [comment]
It looks like OCI uses an HTTP API. Have you tried configuring a Generic_HTTP consumer to send data to OCI? I do not have access to an OCI environment to test with at the moment, but I suspect something like the below declaration should be close.
```json
{
    "class": "Telemetry",
    "OCI": {
        "class": "Telemetry_Consumer",
        "type": "Generic_HTTP",
        "host": "iaas.{{region}}.oraclecloud.com",
        "protocol": "https",
        "port": 443,
        "path": "/20200831/logs/{{logId}}/actions/push",
        "method": "POST",
        "headers": [
            {
                "name": "content-type",
                "value": "application/json"
            },
            {
                "name": "Authorization",
                "value": "`>@/signature`"
            }
        ],
        "signature": {
            "cipherText": "Signature version=\"1\",headers=\"date (request-target) host content-length content-type x-content-sha256\",keyId=\"ocid1.tenancy.oc1..{{unique_id}}/ocid1.user.oc1.{{unique_id}}/{{your_fingerprint}}\",algorithm=\"rsa-sha256\",signature=\"{{your_signature}}\""
        },
        "actions": [
            {
                "JMESPath": {},
                "expression": "{ specVersion: '1.0', logEntryBatches: [{defaultlogentrytime: event_timestamp, source: hostname, type: telemetryEventCategory, entries: [{data: @, id: join('-', [event_timestamp, hostname, telemetryEventCategory])}]}]}"
            }
        ]
    }
}
```

**Comment by kwlooi** [comment]
The suggestion above is a NON-STARTER.
 
I can get the Tenancy OCID, USERID, FINGERPRINT for populating the keyId.  However, the {{signature}} part is not going to work because each POST request requires us to sign the request and the signature string has a date timestamp of request from the header.  In order words, if the POST request was generated by a client using the OCI SDK, it can sign it every time with the date timestamp included in the signature string.  The signature is NOT static.
 
This is not going to be possible for the Telemetry if it is relying only on the hardcoded signature (the signature would become invalid after a while).
 
See here for more details:
 
https://www.ateam-oracle.com/oracle-cloud-infrastructure-oci-rest-call-walkthrough-with-curl
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm

**Comment by dstokesf5** [comment]
Thank you for your feedback. At this time we are focusing Telemetry Streaming on OpenTelemetry use cases, and we are no longer accepting requests for additional consumers. The growing list of supported consumers has become a strain on our limited development resources. If you have a strong business case for a new consumer, I suggest reaching out to product management or F5 support.
