### ISSUE TITLE
Documentation Screenshot example outputs for push consumers

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-telemetry-streaming#52]
### Is your feature request related to a problem? Please describe.
Requesting to have example screenshot for each Push Consumer. Currently only Azure log analytics is shown as example pic.

### Describe the solution you'd like
documentation update with pics

### Describe alternatives you've considered
n/a

### Additional context
It's nice to see example outcomes. Some customers will rely on the API response data whereas other customers (netops) might require access to a dashboard and would benefit from seeing an example screenshot. This way they have an expected outcome or known working example to compare to their lab.

**Comment by dstokesf5** [comment]
Thank you for your feedback. With Telemetry Streaming's growing list of supported consumers (I believe we have already passed 15), it is difficult for us to maintain a high standard of documentation for each consumer. As we identify the most used consumers, we will look into improving the documentation for them. I am closing this issue since we do not have the resources at this time to gather these example images for all supported consumers.
