### ISSUE TITLE
Usage pattern for using TS with BIGIPs already using offbox analytics

### ISSUE THREAD

**Issue by ryn9** [F5Networks/f5-telemetry-streaming#59]
### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like

We need a supported usage pattern for using TS with BIGIPs already using offbox analytics (example - BIGIQ).

Getting AVR data, as described in https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/avr.html, is not possible when offbox analytics are already being sent to another product (example - BIGIQ)

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by dstokesf5** [comment]
I have added AUTOTOOL-1678 to our internal product backlog to look into this further.

**Comment by ryn9** [comment]
@dstokesf5 any update on this matter?

**Comment by dstokesf5** [comment]
After researching this, we determined that BIG-IQ will overwrite the configuration necessary to send AVR data to Telemetry Streaming. This makes it impossible to send AVR data to BIG-IQ and a second location via Telemetry Streaming. If you need to send data to multiple locations that are not BIG-IQ, you can configure multiple consumers to do so.

Our documentation regarding AVR data in Telemetry Streaming was updated to reflect this: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/avr.html

We are continuing discussions with the BIG-IQ team to find a solution. However, at this time, we cannot commit to Telemetry Streaming being able to work around this BIG-IQ behavior. Since we cannot commit to this being resolved in Telemetry Streaming, I am closing this issue.
