### ISSUE TITLE
Provide AVR based metrics through Prometheus consumer

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-telemetry-streaming#73]
### Is your feature request related to a problem? Please describe.
Want ability to report Page load times and RTT for applications and not have to use on box AVR or BIGIQ to get this information.

### Describe the solution you'd like
Would like metrics exposed for page load time, server latency and RTT on a virtual server basis

### Describe alternatives you've considered
Using on box AVR or BIG-IQ

**Comment by jtylershaw** [comment]
I like this idea - and I think I'd love to see it go a bit further.  The "Enhanced Analytics" provided in BIG-IQ 6.0+ would be a great bar to set for this:  https://techdocs.f5.com/kb/en-us/products/big-iq-centralized-mgmt/manuals/product/big-iq-centralized-management-monitoring-and-managing-application-services-6-0-0/3.html#unique_377701420

To go along with being able to stream this data off box - say to an elastic search database - would also be to disable on-box processing of AVR for this same data like the integration with BIG-IQ does.  Great idea @ajgerace!

**Comment by dstokesf5** [comment]
@ajgerace Telemetry Streaming can already stream AVR data: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/avr.html

Can you please elaborate on what data is missing?

**Comment by ajgerace** [comment]
Hi Daniel
I’ve enabled AVR and setup the global settings as per the referenced doc.
Is there something that needs to be changed in the TS declaration to have
them available? Are all consumers supported? I’m working with Prometheus.

Thanks

Anthony

**Comment by dstokesf5** [comment]
@ajgerace AVR data is sent into Telemetry Streaming by configuring AVR to send it to a Telemetry Streaming event listener: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html

Unfortunately, I believe the pull consumers (which includes the Prometheus consumer) do not gather data from event listeners: https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/event-listener.html. I am confirming this behavior and discussing solutions with the developers. I will provide an update once I have more information.

**Comment by dstokesf5** [comment]
I have confirmed that the Prometheus consumer does not support event data. In order to make it work with AVR and other events would require a non-trivial amount of work. I have added this request to our internal product backlog as AUTOTOOL-1962, however it is unlikely to be prioritized for development with out more demand.

If this is a critical issue for you, please contact F5 support as the README recommends: https://github.com/F5Networks/f5-telemetry-streaming#filing-issues-and-getting-help

**Comment by ianwijaya** [comment]
> I have confirmed that the Prometheus consumer does not support event data. In order to make it work with AVR and other events would require a non-trivial amount of work. I have added this request to our internal product backlog as AUTOTOOL-1962, however it is unlikely to be prioritized for development with out more demand.
> 
> If this is a critical issue for you, please contact F5 support as the README recommends: https://github.com/F5Networks/f5-telemetry-streaming#filing-issues-and-getting-help

Thanks @dstokesf5 , been looking for this statement for weeks. I hope we can have this feature soon, and in the meantime can have someone to update our documentation to clearly inform this limitation. 

Thanks, 
Ian

**Comment by meghdivya** [comment]
Hi guys, any ETA for this. It has been a long time pending.

**Comment by dstokesf5** [comment]
There is currently no ETA for this feature.

**Comment by dstokesf5** [comment]
In order to avoid implementing data caching, aggregation, and other features to the Prometheus consumer to handle events, we have decided to focus instead on Open Telemetry export. For the use case of gathering event data, such as AVR, with Prometheus, we recommend sending the data to an Open Telemetry collector. That collector should be configured to receive OTLP and export Prometheus.

https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/setting-up-consumer.html#opent
