### ISSUE TITLE
tmstats support for Splunk format

### ISSUE THREAD

**Issue by walterk82** [F5Networks/f5-telemetry-streaming#81]
### Is your feature request related to a problem? Please describe.
Enable support for tmstats metrics with the regular Splunk Consumer.  The Splunk legacy consumer is too rigidly set and does not support filtering criteria for event listeners.

### Describe the solution you'd like
Splunk "normal" Consumer needs to support additional metric gathering types. Please add support for tmstats and iRules stats for general platform trending.

### Describe alternatives you've considered
Splunk legacy is an option but the way the events are sent over are very hard to consume.

**Comment by dstokesf5** [comment]
At this time we are hesitant to add the data gathered from tmctl to the default output since we would be unable to provide appropriate documentation to users on what the data means and where it is coming from. We were forced to add it to the legacy format for compatibility with the Analytics iApp.

As an alternative, would exposing enough functionality on the [custom endpoint feature](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/custom-endpoints.html) work to solve your use case? I believe this would mostly require being able to specify a POST body.

**Comment by walterk82** [comment]
Looking quickly, I see that path /mgmt/tm/sys/memory/stats is workable using this feature.  I'm trying to figure out how you named to the top level JSON elements by default.

**Comment by dstokesf5** [comment]
Since you are able to get the stats you need with custom endpoints, I am closing this issue. Feel free to open a new issue for converting URL encoded strings to human readable strings.

**Comment by walterk82** [comment]
Thank-you 

https://github.com/F5Networks/f5-telemetry-streaming/issues/95
