### ISSUE TITLE
Cluster status metrics required

### ISSUE THREAD

**Issue by anesmashnyi-godaddy** [F5Networks/f5-telemetry-streaming#99]
### Is your feature request related to a problem? Please describe.
I'd like to monitor Failover status and Sync status of F5 cluster.  The example [here](https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/output-example.html) demonstrates the metrics I need. However, I have nothing suitable in AWS CloudWatch consumer.
How do I monitor cluster status then?

### Describe the solution you'd like
Metrics for Failover status and Sync status of F5 cluster.

### Describe alternatives you've considered
No

### Additional context
No

**Comment by mikeoleary** [comment]
I can replicate this too. In case it helps:

* When I set up TS with the AWS CloudWatch **Logs** consumer, I see log entries with timestamps and a JSON-formatted value that includes the system outputs we expect, including syncStatus and failoverStatus.

* However, when I switch to the AWS CloudWatch **Metrics** consumer, I see only metrics by name, where there are no timestamps. There appears to be no metric for syncStatus or failoverStatus. This is what we care about and want to monitor.

In this case we want to use the Metrics provider, not the Logs provider, and these will eventually be loaded into DataDog. Ideally, we would provide a TS consumer directly into DataDog, and this has also been requested in issue #94

**Comment by anesmashnyi-godaddy** [comment]
Thank you Michael, all settled!

**Comment by nickamon** [comment]
I tested this recently as of 1.33.0 and it is the same behavior.  The syncStatus and failoverStatus is available as part of the Logs consumer but not the Metrics consumer for CloudWatch.  I'm not sure why this was closed, what is the resolution?

**Comment by mikeoleary** [comment]
@nickamon you asked why this issue was closed and what was the resolution. From memory, I worked with the customer who created this issue. 

If I recall correctly, eventually we accepted the fact that _syncStatus_ and _failoverStatus_ aren't really **metrics**. I.e., it's not a value you would graph over time or collect at a fixed interval. They are **events** that do not occur at predictable intervals but rather, obviously, when the system changes from Active to Standby or from "in sync" to "not in sync". So we accepted that if we want to see these, we need to use the AWS CloudWatch Logs consumer, not the Metrics consumer.
